In [3]:
import numpy as np

[20] Here’s a couple of exercises for you to practice your NumPy and Python skills. First,
make the following two arrays:

happy = np . a r r a y ( [ [ 1 , 1 , 1 , 2 ] , [ 2 , 2 , 2 , 3 ] , [ 3 , 3 , 3 , 4 ] , [ 4 , 4 , 4 , 5 ] )

sad = np . a r r a y ( [ [ 1 , 3 ] , [ 2 , 4 ] , [ 5 , 7 ] , [ 6 , 8 ] , [ 9 9 , 1 0 0 ] )

(a) Use slice notation to print the 2nd column from the 1st row in happy.

(b) Can you add happy and sad together? Why or why not?

(c) Add 5 to each element in sad.

(d) Subtract 1 from the last element in the last row of happy.

(e) Make a new array using slice notation that looks like happy but does not include the
first column and the last row.

In [8]:
happy = np.array([ [1,1,1,2],[2,6,2,3],[3,3,3,4],[4,6,4,5]] )
#changed values to make sure i was getting the second col and row. 

sad = np.array([ [1,3],[2,4],[5,7],[6,8],[99,100]] )

print(happy)
poop = happy[:,1]
print(poop)
"""
Can you add happy and sad together? Why or why not?
No you cannot add the two together since they are not the same size matrix
"""

five_add = np.add(5, sad)
print("\n")
print(five_add)
sub1 = np.add(-1,happy[-1,-1])
print(sub1)
print("\n")
confused = np.array([ [1,1,2],[6,2,3],[3,3,3] ])
print(confused)

[[1 1 1 2]
 [2 6 2 3]
 [3 3 3 4]
 [4 6 4 5]]
[1 6 3 6]


[[  6   8]
 [  7   9]
 [ 10  12]
 [ 11  13]
 [104 105]]
4


[[1 1 2]
 [6 2 3]
 [3 3 3]]


In [18]:
def checkaverage(arr):
      return np.where(arr >= np.average(arr), arr, 0)
checkaverage(np.array([ [9,2,3],[4,5,6] ]))

array([[9, 0, 0],
       [0, 5, 6]])